#!/usr/bin/env python3
"""Generate foundry.toml + build.sh + nexus.scope.md from .tools/fetch_report.json."""

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
REPORT = json.load(open(ROOT / ".tools/fetch_report.json"))

# Filter to successful pulls
contracts = [r for r in REPORT if r.get("status") in ("ok", "skipped_existing") and r.get("directory")]
contracts.sort(key=lambda r: r["directory"])

profile_blocks = []
build_lines = ['#!/bin/bash', '# Generated. Builds each in-scope contract under its own Foundry profile.', 'set +e', 'echo "Building {} contracts individually..."'.format(len(contracts)), 'echo ""', 'OK=0; FAIL=0; FAILED=()']

for c in contracts:
    rel = c["directory"]                  # src/<Name>_<addr4>
    name_addr = Path(rel).name            # <Name>_<addr4>
    profile = f"contract_{name_addr}"
    solc = c.get("compiler_version") or "0.8.20"
    runs = c.get("runs") or 200
    optimizer = "true" if c.get("optimization_used") else "false"
    evm = c.get("evm_version") or "default"
    via_ir = bool(c.get("viaIR"))

    # Per-contract remappings:
    #   1. If the verified solc input shipped explicit `settings.remappings` (Foundry-style
    #      projects), use those — they are relative to the contract's source root.
    #   2. Otherwise, auto-detect top-level @-prefixed dirs inside src/<rel>/.
    contract_dir = ROOT / rel
    remap = []
    explicit = c.get("remappings") or []
    if explicit:
        for entry in explicit:
            if "=" not in entry:
                continue
            key, target = entry.split("=", 1)
            target = target.strip().lstrip("./")
            if not target:
                continue
            # Normalize target to live under src/<rel>/<target>
            full_target = f"{rel}/{target}".rstrip("/") + "/"
            remap.append(f"{key.strip()}={full_target}")
    else:
        for sub in sorted(contract_dir.iterdir()):
            if sub.is_dir() and sub.name.startswith("@"):
                remap.append(f"{sub.name}/={rel}/{sub.name}/")
    remap_toml = ", ".join(f'"{r}"' for r in remap)

    block = [
        f"# {c['contract_name']} ({c['address']})  {c['chain']}  {'proxy → ' + c['implementation'] if c.get('proxy') else 'direct'}",
        f"[profile.{profile}]",
        f'src = "{rel}"',
        f'out = "out/{profile}"',
        f'cache_path = "cache/{profile}"',
        f'test = "test/_disabled"',
        f'script = "script/_disabled"',
        f'libs = ["lib/_disabled"]',
        f'solc = "{solc}"',
        f"optimizer = {optimizer}",
        f"optimizer_runs = {runs}",
        f"remappings = [{remap_toml}]",
    ]
    if evm and evm.lower() not in ("default", ""):
        block.append(f'evm_version = "{evm.lower()}"')
    if via_ir:
        block.append("via_ir = true")
    profile_blocks.append("\n".join(block))

    build_lines += [
        f'echo "[$((OK+FAIL+1))/{len(contracts)}] {name_addr}"',
        f'FOUNDRY_PROFILE={profile} forge build --silent && OK=$((OK+1)) || {{ FAIL=$((FAIL+1)); FAILED+=("{name_addr}"); }}',
    ]

build_lines += [
    'echo ""',
    'echo "=== summary ==="',
    'echo "ok=$OK fail=$FAIL total=$((OK+FAIL))"',
    'if [ $FAIL -gt 0 ]; then',
    '  echo "failed profiles:"',
    '  printf "  %s\\n" "${FAILED[@]}"',
    'fi',
    'exit $FAIL',
]

(ROOT / "foundry.toml").write_text(
    "# Generated by .tools/gen_foundry.py — one profile per in-scope contract.\n"
    "# Default profile compiles nothing on its own; each contract has its own profile.\n\n"
    "[profile.default]\n"
    'src = "src/_unused"\n'  # placeholder so default doesn't touch every contract
    'out = "out"\n'
    'libs = ["lib"]\n'
    'test = "test"\n'
    'script = "script"\n'
    'cache_path = "cache"\n'
    'solc = "0.8.20"\n'
    'optimizer = true\n'
    'optimizer_runs = 1000\n\n'
    + "\n\n".join(profile_blocks) + "\n"
)

build_path = ROOT / "build.sh"
build_path.write_text("\n".join(build_lines) + "\n")
build_path.chmod(0o755)

# nexus.scope.md — every .sol under each in-scope dir
scope_lines = []
for c in contracts:
    d = ROOT / c["directory"]
    for sol in sorted(d.rglob("*.sol")):
        scope_lines.append(str(sol.relative_to(ROOT)))

# Filter to "in-scope" contract files only — drop vendored deps that came with each pull
def in_scope_path(p: str) -> bool:
    # Anything under @openzeppelin/, @layerzerolabs/, @chainlink/, etc. is a dep, not in scope.
    parts = Path(p).parts
    for part in parts:
        if part.startswith("@"):
            return False
    # Lista source typically lives under contracts/ within each <Name>_<addr4>/ dir
    return True

scope_filtered = [p for p in scope_lines if in_scope_path(p)]
(ROOT / "nexus.scope.md").write_text("\n".join(scope_filtered) + "\n")

print(f"Wrote foundry.toml with {len(contracts)} profiles")
print(f"Wrote build.sh ({len(build_lines)} lines)")
print(f"Wrote nexus.scope.md with {len(scope_filtered)} in-scope source files (filtered from {len(scope_lines)} total)")
